---
# Fallbacks; override in group_vars/all.yml.
mssql_instance_name: "MSSQLSERVER"
mssql_edition: "Developer"
mssql_mixed_mode: true
mssql_business_db: "BusinessDB"
mssql_installer_path: 'C:\Installers\SQL2019-Dev\setup.exe'
